/* Generated By:JavaCC: Do not edit this line. LPLParserConstants.java */
package lpl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LPLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 8;
  /** RegularExpression Id. */
  int LPAREN = 9;
  /** RegularExpression Id. */
  int RPAREN = 10;
  /** RegularExpression Id. */
  int DEF = 11;
  /** RegularExpression Id. */
  int INT = 12;
  /** RegularExpression Id. */
  int BOOLEAN = 13;
  /** RegularExpression Id. */
  int UNIT = 14;
  /** RegularExpression Id. */
  int TRUE = 15;
  /** RegularExpression Id. */
  int FALSE = 16;
  /** RegularExpression Id. */
  int NOT = 17;
  /** RegularExpression Id. */
  int LSQBR = 18;
  /** RegularExpression Id. */
  int RSQBR = 19;
  /** RegularExpression Id. */
  int LBRACE = 20;
  /** RegularExpression Id. */
  int RBRACE = 21;
  /** RegularExpression Id. */
  int SEMICOLON = 22;
  /** RegularExpression Id. */
  int ASSIGN = 23;
  /** RegularExpression Id. */
  int AND = 24;
  /** RegularExpression Id. */
  int OR = 25;
  /** RegularExpression Id. */
  int LESSTHAN = 26;
  /** RegularExpression Id. */
  int EQUALS = 27;
  /** RegularExpression Id. */
  int DIV = 28;
  /** RegularExpression Id. */
  int PLUS = 29;
  /** RegularExpression Id. */
  int MINUS = 30;
  /** RegularExpression Id. */
  int TIMES = 31;
  /** RegularExpression Id. */
  int DOT = 32;
  /** RegularExpression Id. */
  int ISNULL = 33;
  /** RegularExpression Id. */
  int LENGTH = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int NEW = 36;
  /** RegularExpression Id. */
  int ELSE = 37;
  /** RegularExpression Id. */
  int IF = 38;
  /** RegularExpression Id. */
  int WHILE = 39;
  /** RegularExpression Id. */
  int OUTPUT = 40;
  /** RegularExpression Id. */
  int OUTCHAR = 41;
  /** RegularExpression Id. */
  int RETURN = 42;
  /** RegularExpression Id. */
  int ID = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "<INTEGER_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"def\"",
    "\"int\"",
    "\"bool\"",
    "\"unit\"",
    "\"true\"",
    "\"false\"",
    "\"!\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\"==\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\".\"",
    "\"isnull\"",
    "\"length\"",
    "\",\"",
    "\"new\"",
    "\"else\"",
    "\"if\"",
    "\"while\"",
    "\"output\"",
    "\"outchar\"",
    "\"return\"",
    "<ID>",
  };

}
